### ISSUE TITLE
Bold names in bibliography

### ISSUE THREAD

**Issue by mglev1n** [HanZhang-psych/CV#6]
In the final CV output the name "Zhang" is bolded within the bibliography sections, however I'm unable to replicate this functionality when using the provided files. It seems like the name is formatted within the .bib files to be bolded using `{\bf Zhang}` - are there any additional files or settings within the RMarkdown document needed to enable this functionality?

**Comment by HanZhang-psych** [comment]
Hi @mglev1n ,

You are correct that the bold font is specified in the .bib files. But I'm not aware of any more specifications other than that.  I uploaded the .tex file and you can compare it with yours to see if the format is correctly specified. To save the .tex file, add `keep_tex: yes` to your header and knit. E.g.,

```
output: 
  vitae::awesomecv:
    pandoc_args: ["--lua-filter=multiple-bibliographies.lua"] 
    keep_tex: yes
```

Hope this helps!
Han
